//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsPrinter.ServiceReferencePrinter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePrinter.IPrinter")]
    public interface IPrinter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinter/GetAmountByUserId", ReplyAction="http://tempuri.org/IPrinter/GetAmountByUserIdResponse")]
        int GetAmountByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinter/GetAmountByUserId", ReplyAction="http://tempuri.org/IPrinter/GetAmountByUserIdResponse")]
        System.Threading.Tasks.Task<int> GetAmountByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinter/AddAmountByUserId", ReplyAction="http://tempuri.org/IPrinter/AddAmountByUserIdResponse")]
        int AddAmountByUserId(int userId, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrinter/AddAmountByUserId", ReplyAction="http://tempuri.org/IPrinter/AddAmountByUserIdResponse")]
        System.Threading.Tasks.Task<int> AddAmountByUserIdAsync(int userId, int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrinterChannel : WindowsFormsPrinter.ServiceReferencePrinter.IPrinter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrinterClient : System.ServiceModel.ClientBase<WindowsFormsPrinter.ServiceReferencePrinter.IPrinter>, WindowsFormsPrinter.ServiceReferencePrinter.IPrinter {
        
        public PrinterClient() {
        }
        
        public PrinterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrinterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrinterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAmountByUserId(int userId) {
            return base.Channel.GetAmountByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<int> GetAmountByUserIdAsync(int userId) {
            return base.Channel.GetAmountByUserIdAsync(userId);
        }
        
        public int AddAmountByUserId(int userId, int amount) {
            return base.Channel.AddAmountByUserId(userId, amount);
        }
        
        public System.Threading.Tasks.Task<int> AddAmountByUserIdAsync(int userId, int amount) {
            return base.Channel.AddAmountByUserIdAsync(userId, amount);
        }
    }
}
